# 公共配置
spring:
  profiles:
    # active: @active-profile@
    active: dev
  application:
    name: dm-system-ui
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  # 自定义redisson配置
  redisson:
    # 自定义的key，RedissonConfig中配置使用
    type: single
  servlet:
    multipart:
      # 单文件上传大小
      max-file-size: 5MB
      # 总文件上传大小
      max-request-size: 10MB

# 日志级别
logging:
  level:
    com.dm:

# dubbo配置，参考：https://dubbo.apache.org/zh/docs/v2.7/user/references/
dubbo:
  application:
    name: dm-system-ui
  protocol:
    port: 20881
    name: dubbo
  # 注册中心配置
  registry:
    # 单机配置方法1：
    # address: zookeeper://127.0.0.1:2181
    # 单机配置方法2：
    protocol: zookeeper
    address: 127.0.0.1:2181
    # 集群配置方法1：
    # address: zookeeper://192.168.186.130:2181?backup=192.168.186.131:2181,192.168.186.132:2181
    # 集群配置方法2(未验证)：
    # protocol: zookeeper
    # address: 127.0.0.1:2181，127.0.0.1:2182，127.0.0.1:2183
    # 超时时间
    timeout: 10000
  # 消费者配置
  consumer:
    # 关闭所有服务的启动时检查：（没有提供者时，启动报错）
    check: false
    # 超时时间
    timeout: 10000
    # 统一配置版本
    version: 1.0.0
    # 统一配置分组
    group: dubbo



