# 公共配置
spring:
  profiles:
    # active: @active-profile@
    active: dev
  application:
    name: dm-system-service
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  # 非web启动
  main:
    web-application-type: none
# mybatis配置
mybatis:
  # classpath*:能加载多个路径下的资源文件
  mapper-locations: classpath*:com/dm/mapper/*.xml
  type-aliases-package: com.dm
  configuration:
    # mybatis 打印SQL到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
# 日志配置
logging:
  level:
    com.dm:
# dubbo配置，参考：https://dubbo.apache.org/zh/docs/v2.7/user/references/
dubbo:
  application:
    name: dm-system-service
  protocol:
    port: 20880
    name: dubbo
  # 注册中心配置
  registry:
    # 单机配置方法1：
    # address: zookeeper://127.0.0.1:2181
    # 单机配置方法2：
    protocol: zookeeper
    address: 127.0.0.1:2181
    # 集群配置方法1：
    # address: zookeeper://192.168.186.130:2181?backup=192.168.186.131:2181,192.168.186.132:2181
    # 集群配置方法2(未验证)：
    # protocol: zookeeper
    # address: 127.0.0.1:2181，127.0.0.1:2182，127.0.0.1:2183
    # 超时时间
    timeout: 10000
  # 消费者配置
  consumer:
    # 关闭所有服务的启动时检查：（没有提供者时，启动报错）
    check: false
    # 超时时间
    timeout: 10000
  # 提供者配置
  provider:
    # 超时时间
    timeout: 10000
    # 统一配置版本
    version: 1.0.0
    # 统一配置分组
    group: dubbo




